# Project language
language: php

# PHP version
php:
  - 7.2

# Allows use container-based infrastructure
sudo: false

# Start mysql service
#ervices:
#  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  sonarcloud:
    organization: "adshares-github"
    token:
      secure: "lvjdb5liH9upaIXHVnKuUSBvWJAw5LBIknz/CT0lw6oC+Lq3nHryqMoa5VvIUCKlvmH9WPa9Y7/SY2KPX/3e9Zzu5YQLHA4qg0iRt2nNF1BEjRPpRf3hmEwaG5p9rDQrvgzJMeJmM6FRG2B4HPSs9WBCVRHI5H6oUaI7phlEGfATFWVsM1JvMSlL391ufHhJott/u4sxZf3Kr9KoWsdmdUfR1LijZd/x5dO+204V3dgCeI7+g74/I60Rj1AKE1/SzELmY4bnBFwB1ZkAVfVJ5ZrHkAVjdnLzuuOrGZEeieNBT7wc7espHHwX3hXecY3RLWENwMpGgh/FBa8X30LDLIUap/6/I3x24sJg3y53NL3kicFxiLCAeCsZE+7YgIcs5+dNpvOCx0A5m0ddGlSMLYFwnOHmJySjKkPEcLdmYOVe1W4ViUc4a3fhIhVQwLcWvK9PBGNBXcx/au74WNMgu+UoiqXsL6OsPIIUlz0SsXuXI1H24pN+ouZY7Uu0buxnZc0rJJo2pPAWJECVbcSpSgTs3T7B6mXpB8FLsoCYMCr1l1ESZOypiJWvxXbZU6YWGxZvFiGOsWkmkot9EaHppHaSnyfKrPZo6XNGrhg//LT1q2O0HpLf8k+qeoXE6VJmFcEaMfqDBTI8fnPKr9Qp4Mg2XOy+xJOJtjuET2X1b1Y="
    github_token:
      secure: "OJPwpsbNxubGGaIMTchemK4KP1aU0mmna6X48S511yc7g/14D5rKLedzyYNy+8coFg81DX7Zg8BMdkTwp0d3pj6NfJvkK6BGjTUN+uwyPjUBNGrScncK3uvGYL/n8LMMrFTC/6GIF2B822h+dp8txJJ76pKlw/p1BzhxGt/PsKGn/+MOwiB0Ovy3XcJdrGvpEeKvLKZZzIO6R1isQIgo5coTFwxruUVVRC9j8pOGrFF6Ofeu1wcb28A1Y77rRRzoRsGPY5vTT83kA52Q4mT8vZGqfIwiD7G8nyfyeeuk+oaQwQ+Gp9wUUKlvtmFAtuhHBbxJrE6cRGYW25ABk6wVxrN9Md/G5oKg2bYlnzv3FFMxHdZKopxKDb+2fil238WozdmxTKFa7w+3X7E/p6+ATMi0asi/MN5ONhMJSe/6932zbop44yA7xfRC3hOTjvYaiwUDoicvvo6lBO/TxaKJzsBAAs3sXrxeuBx/npBkGPcTZhECi+QcX0J9OjcJl9w95/yLmrzsftGchnOWkCwj2QsUUsn47sduQZ2pgZCq+xXbw7oqTfGfo2B0yT2NmsH/Wy4Y1lJL63Cy2sxhaKi84WSvSRxuiKcK/UC6OXcHE+4JWRVJ0+IUjj+hU0onUWXDY2o3eiz7Ql/GQI7AfxwYjMSqOZfo/as75bwhZu4ARg0="

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install --no-ansi --no-scripts
  - composer run-script install-codestandards
  - php artisan ide-helper:generate
  #- cp app/config/parameters.yml.dist app/config/parameters.yml
  #- php bin/console doctrine:database:create --env=test
  #- php bin/console doctrine:schema:create --env=test
  #- php bin/console doctrine:fixtures:load -n --env=test

stages:
  - build
  - quality
  - test
#  - name: deploy
#      if: branch = master

jobs:
  include:
    # PHP Lint: check syntax errors in all PHP files
    - stage: build
      script: ./bin/vendor/parallel-lint --no-colors --blame --exclude vendor .
    # SensioLabs Security Checker: check dependencies with known security vulnerabilities
    #- stage: build
    #  script: ./bin/vendor/security-checker security:check
    # PHP_CodeSniffer: check PHP compatibility
    - stage: quality
      script: ./bin/vendor/phpcs -s app --standard=PHPCompatibility
    # PHP_CodeSniffer: check PSR2 standard
    - stage: quality
      script: ./bin/vendor/phpcs -s app --standard=PSR2
    # PHP Static Analysis Tool
    - stage: quality
      script: ./bin/vendor/phpstan --no-ansi --no-progress analyse -c phpstan.neon -l 7 app
    # Sonar Qube
    - stage: quality
      script: sonar-scanner
    # PHP unit tests
    - stage: test
      script:
        - alias php='php -dzend_extension=xdebug.so'
        - alias phpunit='php ./bin/vendor/phpunit'
        - phpunit --configuration phpunit.xml tests

# After a build, send email notification with the build results
notifications:
  email: false
  slack:
    rooms:
      secure: "Y8RTLtFmkDyWd4U17IJsu51VyLhGpRDQeynzJpmXsj4m7Gv6cYjCwdqAox90rCsudeRXPCvLqOPTujZ5cj0qoXIkfKPwAJ1GeHEjxPL6oUO+UF9SnWliL8b4JGUw/QHFqT0VWhgfE0l+QYfHMEAarGFzM03AEyDVkSuVEtbWzQtjvNpe+CCVu8QGzqOJcTrPQ9zjFOwCPc69dIHKsPY+6baFqnx0/GQAx1FGWoRt5iwQdvWoPJ7qajP9kOY7b8wEE/R/9Wfx4YWXgT/fhpYw/cX+jwexlayoCyFC1JpvbEWcS+A9wsOv9+rRptJzNAnL6Z9ZZtfJj2YRIxg1/91ddGDX9QiMCC/Ia/T04DDQizPQRDoDc3qa2a8rZqqMrxwlsUz8qEW8EQnrdM4AuJp4SFX/OMUKzh6zGWglb4BrrRTsgHVJZpjGUVn2zkTnpfGZ+9LsvawC40bgdgNTt4Ty7yvzwTVYwfK5k4gIiuo4wfRXybdhPTTFo0dmF72Bad7GBjjhTeOG0Q1HK3ErRUHN3pD8OBBoNlfsKh6QQnBCwSKAV9ZRyBDvUiYoe14n3+1GVSddKKCuZj0TmvQo7drFg2cpXcU79UmssP3aKXuv2Ew7csxj7aaz8E8eywnDIWX0mwCDOUD+TmoThlvIZufJVPy8mEmzZALQTg5+GBxJggw="
    on_success: change
    on_failure: always
